- name: sshd restart
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true

- name: Make sure rsyncd is running
  ansible.builtin.service:
    name: rsync
    state: started
    enabled: true
